[project]
name = "proslides"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "django-cors-headers>=4.9.0",
    "django-filter>=25.2",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-yasg>=1.21.11",
    "environs>=14.3.0",
    "factory-boy>=3.3.3",
    "freezegun>=1.5.5",
    "requests>=2.32.3",
    "pillow>=12.0.0",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.11.1",
    "pytz>=2025.2",
]

[dependency-groups]
dev = [
    "django-extensions>=4.1",
    "graphviz>=0.21",
    "pydot>=4.0.1",
]
