# Generated by Django 5.2.8 on 2025-12-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0006_option_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order']},
        ),
    ]
