# Generated by Django 5.2.8 on 2025-12-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_fix_rust_session_id_columns'),
        ('office', '0010_alter_option_order_and_more'),
    ]

    operations = [
    ]
