# Generated by Django 5.2.8 on 2025-12-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0011_merge_20251231_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='author',
        ),
    ]
