# Generated by Django 5.2.8 on 2026-01-08 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0012_remove_quiz_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='access_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='access_code must be 5-12 chars and use letters and numbers only', regex='^[A-Za-z0-9]{5,12}$')]),
        ),
    ]
