[package]
name = "facade"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
actix = "0.13"
actix-rt = "2.11.0"
actix-web = "4"
actix-web-actors = "4"
chrono = { version = "0.4.42", features = ["clock"] }
redis = {version="0.32.7", features = ["tokio-comp"] }
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0.100"

[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = [
    "v4",
]
